In [107]:
import pandas as pd
import numpy as np
import math
from sklearn.metrics.pairwise import cosine_similarity
result = pd.read_csv("C:\\Users\\THE TAM\\Desktop\\data.csv")
#chuyen Dataframe sang Numpy
m_u = result.values[:,:]
Sim = np.zeros((result.shape[0],result.shape[0]))
print("---------------------------------------------------------------------------------------------------------------")

# tính sim(u,u')
def cal_each_sim(M,i,j):
    N=M.copy()   
    t=0
    m=0
    tong=0
    tich_a=0
    tich_b=0
    for k in range(0,M.shape[1]): 
        if( (pd.isnull(M[i,k])==False) and (pd.isnull(M[j,k])==False) ):
            a=float(M[i,k])
            b=float(M[j,k])
            #TINH TU SO
            tong+=(M[i,k]*M[j,k])
            # TINH MAU SO
            tich_a+= a**2
            tich_b+= b**2
    M=pd.DataFrame(M).dropna(axis=1)
    t=tong
    m = np.sqrt(tich_a*tich_b);
    return t/m
# gán sim(u,u') vào ma trận user, item
def cal_sum_sim(M):
    #print("--------SHAPE----------")
    #print(M.shape[0])
    for i in range(0,M.shape[0]):
        for j in range (0,M.shape[0]):
            if(i==j):
                Sim[i,j]=1;
            else:
                Sim[i,j]=cal_each_sim(M,i,j);
    return Sim;
# tìm K láng giềng
# y tuong: sắp xếp Sim(u,u') tăng dần, sau đó lấy hai giá trị Sim cao nhất, không lấy giá trị 1 ( vì đó là Sim(u,u) luôn =1 )
def findK(C,m,K,sort_m):
    value=0
    u_ner = np.zeros(K)
    for k in range(1,K+1):
        value = sort_m[m,C.shape[1]-k-1]
        for u_phay in range(0,C.shape[1]):
            if(value == C[m,u_phay]):
                u_ner[k-1]=u_phay
                break       
    return u_ner
# Ma tran du doan
def predic_M(M,K):
    cosin = cal_sum_sim(M)
    #print(cosin)
    sort_m = np.sort(cosin)
    for u in range(0,M.shape[0]):
        u_ner = findK(cosin,u,K,sort_m)
        for i in range(0,M.shape[1]):
            if(pd.isnull(M[u,i])==True):
                tu=0
                mau=0
                for j in range(K):
                    a=int(u_ner[j])
                    tu+= (cosin[u,a]) * (M[a,i])
                    mau+=(cosin[u,a])
                M[u,i] = tu/mau  
                #print(M[u,i])
    return M


print("---MA TRAN BAN DAU-----")
print(d)
print("---MA TRAN USER DU DOAN-----")
for i in range(10):
    m = predic_M(m,2)
    m=np.around(m)
print(m)       
print("----------------------------------------------------------------------------------")
print("----MA TRẬN ITEM BAN ĐẦU")
#Cách làm như ma trận user, chỉ cần chuyển vị ma trận ban đầu (ma trận d) thì ta sẽ có ma trận theo item
m_i = d.T
print(m_i)
print("---MA TRAN ITEM DU DOAN-----")



                         

               
    
            
    

        
        
    
    


    

---------------------------------------------------------------------------------------------------------------
---MA TRAN BAN DAU-----
[[3.02736074 2.         2.         4.50684019 1.        ]
 [1.         3.         5.         4.         1.96571316]
 [5.         5.         2.         5.         3.        ]
 [5.         2.                nan 4.         5.        ]
 [4.         3.47726751 2.         4.4924225  4.        ]]
---MA TRAN USER DU DOAN-----
[[3. 2. 2. 5. 1.]
 [1. 3. 5. 4. 2.]
 [5. 5. 2. 5. 3.]
 [5. 2. 2. 4. 5.]
 [4. 3. 2. 4. 4.]]
----------------------------------------------------------------------------------
----MA TRẬN ITEM BAN ĐẦU
[[3.02736074 1.         5.         5.         4.        ]
 [2.         3.         5.         2.         3.47726751]
 [2.         5.         2.                nan 2.        ]
 [4.50684019 4.         5.         4.         4.4924225 ]
 [1.         1.96571316 3.         5.         4.        ]]
---MA TRAN ITEM DU DOAN-----


In [94]:
print(d.shape[0])

5


In [82]:
print(d.shape[1])

5
